### PR TITLE
Feature/fix highlights

### LINKED ISSUE #99: Highlighting not working on local machine
Highlighting has never worked on my local machine, should apply a fix so it will work for development.

### PR DESCRIPTION
**Pull request by jechols**
Fixes #99

### CODE REVIEW

File: core/static/js/highlight.js [hunk 1]
```diff
@@ -23,12 +22,13 @@
                     var coordinates = all_coordinates["coords"][word];
                     for (k in coordinates) {
                         var v = coordinates[k];
-                        div.append("<div style='position: absolute; " +
-    "TOP: " +  (v[1] * vScale) + '%; ' +
```
Comment (jduss4) [inline core/static/js/highlight.js]: Bless you.  May the gods of indentation smile upon you in the coming season.
