### PR TITLE
Feature/highlight fix

### LINKED ISSUE #246: Search highlighting broken
Search highlighting seems not to be completely working on the page view, though it is in the thumbnail view. 

For example, see below, with highlighted words. 

screen shot 2016-07-29 at 9 23 11 am

When I click on the first result, only one of the words appears to be highlighted

screen shot 2016-07-29 at 9 24 23 am

I thought at first it was only the first word in the list being highlighted, but that does not seem to be the case. 

screen shot 2016-07-29 at 9 25 32 am

I first noticed this while testing @jduss4 's advanced search branch, but it exists in Master too, so it's not that branch.

### PR DESCRIPTION
**Pull request by jechols**
Fixes #246 

I could be persuaded to un-rewrite the highlight logic; I did that primarily because I couldn't figure out the problem.  But the new logic in `page.js` matches `highlight.js` more closely, so I'd prefer to keep it just in case.

I also changed the `.load` to `.on("load")` as `.load` has been deprecated.

### CODE REVIEW

File: core/static/js/page.js [hunk 1]
```diff
@@ -101,20 +101,12 @@
...
-                        $.each(coordinates, function(index, value) {
-                            addOverlay(viewer,
-                                       value[0]*scale,
-                                       value[1]*scale,
-                                       value[2]*scale,
-                                       value[3]*scale);
-                        });
-                    }
-                }
+                var boxes = [];
```
Comment (jduss4) [inline core/static/js/page.js]: have you tried any examples that would have run up against their `word!=""` check?

Comment (jechols) [reply core/static/js/page.js]: If that check is necessary, we need to add it to highlight.js, since that script is responsible for the search result highlighting.  Actually, though, we can make that never possible by fixing the split.  BRB.

Comment (jechols) [reply core/static/js/page.js]: New commit uses /\s+/ for the split in both files, so "" is not possible.

Comment (jduss4) [reply core/static/js/page.js]: oh duh, thanks

Comment (jduss4) [reply core/static/js/page.js]: thanks!
